#!/usr/bin/env python3
"""Count open tasks (- [ ]) across all .md files at each of the last N commits."""

import subprocess
import sys
import math
import os
from datetime import datetime, timedelta

VAULT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_FILE = os.path.join(VAULT_ROOT, "Notes", "Open Tasks Over Time.md")
TICK = "```"

def run(cmd, **kwargs):
    return subprocess.run(cmd, capture_output=True, text=True, **kwargs)

def count_tasks_at_commit(commit):
    # Use -z for NUL-separated output — avoids all path quoting issues (non-ASCII, quotes, spaces)
    result = subprocess.run(
        ["git", "ls-tree", "-r", "-z", "--name-only", commit],
        capture_output=True
    )
    total = 0
    for raw in result.stdout.split(b"\x00"):
        if not raw:
            continue
        filepath = raw.decode("utf-8", errors="replace")
        if not filepath.endswith(".md"):
            continue
        if filepath.startswith(".claude/") or filepath.startswith("__scripts__/"):
            continue
        if filepath in ("CLAUDE.md", "Notes/Open Tasks Over Time.md"):
            continue
        if filepath.startswith("Archive/"):
            continue
        content = run(["git", "show", f"{commit}:{filepath}"])
        if content.returncode != 0:
            continue
        in_code_block = False
        for line in content.stdout.splitlines():
            if line.strip().startswith("```"):
                in_code_block = not in_code_block
            if not in_code_block and "- [ ]" in line:
                total += 1
    return total

def main(mode="month"):
    log = run(["git", "log", "--format=%H %as"])
    all_commits = []
    for line in log.stdout.strip().splitlines():
        parts = line.split()
        if len(parts) == 2:
            all_commits.append((parts[0], parts[1]))

    if mode == "month":
        cutoff = (datetime.now() - timedelta(days=20)).strftime("%Y-%m-%d")
        seen_dates = set()
        commits = []
        for sha, date in all_commits:
            if date >= cutoff and date not in seen_dates:
                commits.append((sha, date))
                seen_dates.add(date)
        commits.reverse()
    else:
        n = int(mode)
        total = len(all_commits)
        if total <= n:
            commits = all_commits
        else:
            indices = [int(i * (total - 1) / (n - 1)) for i in range(n)]
            commits = [all_commits[i] for i in indices]
        commits.reverse()

    results = []
    for sha, date in commits:
        count = count_tasks_at_commit(sha)
        results.append((date, count))
        print(f"{date}: {count}", file=sys.stderr)

    dates = [r[0] for r in results]
    counts = [r[1] for r in results]

    months = {"01":"Jan","02":"Feb","03":"Mar","04":"Apr","05":"May","06":"Jun",
              "07":"Jul","08":"Aug","09":"Sep","10":"Oct","11":"Nov","12":"Dec"}
    short_dates = []
    for d in dates:
        parts = d.split("-")
        short_dates.append(f"{int(parts[2])} {months.get(parts[1], parts[1])}")

    label = f"last {len(results)} days" if mode == "month" else f"last {len(results)} commits"
    max_count = max(counts) if counts else 100
    y_max = math.ceil(max_count * 1.1 / 100) * 100
    axis_labels = ", ".join('"' + d + '"' for d in short_dates)
    counts_str = ", ".join(str(c) for c in counts)

    # Last 4 values newest-first for trend frontmatter
    recent = list(reversed(counts))[:4]
    today = datetime.now().strftime("%Y-%m-%d")

    fm_lines = ["---", f"date: {today}"]
    for i, v in enumerate(recent):
        fm_lines.append(f"d{i}: {v}")
    fm_lines.append("---")
    frontmatter = "\n".join(fm_lines)

    table_rows = "\n".join(f"| {d} | {c} |" for d, c in reversed(list(zip(dates, counts))))

    content = (
        f"{frontmatter}\n"
        "\n"
        "# Open Tasks Over Time\n"
        "\n"
        "Tracks the number of open tasks (`- [ ]`) across the vault, one commit per day for the last 20 days. "
        "Generated by `__scripts__/count_open_tasks.py`.\n"
        "\n"
        "To regenerate: `python3 __scripts__/count_open_tasks.py` "
        "(or pass a number for full-history sampling, e.g. `python3 __scripts__/count_open_tasks.py 30`)\n"
        "\n"
        f"{TICK}mermaid\n"
        "%%{init: {'themeVariables': {'xyChart': {'plotColorPalette': '#ff6600'}}}}%%\n"
        "xychart-beta\n"
        f'    title "Open Tasks Over Time ({label})"\n'
        f"    x-axis [{axis_labels}]\n"
        f'    y-axis "Open Tasks" 0 --> {y_max}\n'
        f"    line [{counts_str}]\n"
        f"{TICK}\n"
        "\n"
        "| Date | Open Tasks |\n"
        "|------|-----------|\n"
        f"{table_rows}\n"
    )

    with open(OUTPUT_FILE, "w") as f:
        f.write(content)

    print(f"Updated {OUTPUT_FILE}")
    if len(recent) > 1:
        print(f"Latest: {recent[0]} tasks ({recent[0] - recent[1]:+d} vs yesterday)")

if __name__ == "__main__":
    arg = sys.argv[1] if len(sys.argv) > 1 else "month"
    try:
        int(arg)
        main(mode=arg)
    except ValueError:
        main(mode=arg)
